stages:
  - lint
  - release

install:
  stage: lint
  script:
  - flutter doctor
  - flutter pub get
  tags:
    - flutter

deploy-check:
  stage: release
  script:
    - |
      if [ -z "${PUB_DEV_PUBLISH_ACCESS_TOKEN}" ]; then
        echo "Missing PUB_DEV_PUBLISH_ACCESS_TOKEN environment variable"
        exit 1
      fi

      if [ -z "${PUB_DEV_PUBLISH_REFRESH_TOKEN}" ]; then
        echo "Missing PUB_DEV_PUBLISH_REFRESH_TOKEN environment variable"
        exit 1
      fi

      if [ -z "${PUB_DEV_PUBLISH_TOKEN_ENDPOINT}" ]; then
        echo "Missing PUB_DEV_PUBLISH_TOKEN_ENDPOINT environment variable"
        exit 1
      fi

      if [ -z "${PUB_DEV_PUBLISH_EXPIRATION}" ]; then
        echo "Missing PUB_DEV_PUBLISH_EXPIRATION environment variable"
        exit 1
      fi

      cat <<EOF > ~/.pub-cache/credentials.json
      {
        "accessToken":"${PUB_DEV_PUBLISH_ACCESS_TOKEN}",
        "refreshToken":"${PUB_DEV_PUBLISH_REFRESH_TOKEN}",
        "tokenEndpoint":"${PUB_DEV_PUBLISH_TOKEN_ENDPOINT}",
        "scopes":["https://www.googleapis.com/auth/userinfo.email","openid"],
        "expiration":${PUB_DEV_PUBLISH_EXPIRATION}
      }
      EOF
    - flutter pub publish --dry-run
  tags:
    - flutter
  only:
    - master
    - /v[0-9]+\.[0-9]+\.[0-9]+.*/

publish:
  stage: release
  script:
    - flutter pub publish -f
  tags:
    - flutter
  only:
    - /v[0-9]+\.[0-9]+\.[0-9]+.*/
  except:
    - branches